export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const { url } = req.body;
  if (!url) return res.status(400).json({ error: "No URL provided" });

  const match = url.trim().replace(/\.git$/, "").match(/github\.com[:\/]([^\/]+)\/([^\/]+)/);
  if (!match) return res.status(400).json({ error: "Invalid GitHub URL" });

  const [, owner, repoName] = match;
  const full = `${owner}/${repoName}`;

  async function gh(pathname) {
    const r = await fetch(`https://api.github.com${pathname}`);
    if (!r.ok) {
      const text = await r.text();
      throw new Error(`GitHub API ${r.status}: ${text.slice(0, 100)}`);
    }
    return r.json();
  }

  async function raw(pathname) {
    try {
      const r = await fetch(`https://raw.githubusercontent.com/${full}/${branch}/${pathname}`);
      return r.ok ? r.text() : null;
    } catch { return null; }
  }

  let repoInfo, branch, tree;
  try {
    repoInfo = await gh(`/repos/${full}`);
    branch = repoInfo.default_branch;
    tree = await gh(`/repos/${full}/git/trees/${branch}?recursive=1`);
  } catch (e) {
    return res.status(400).json({ error: e.message });
  }

  const allFiles = tree.tree.filter(t => t.type === "blob").map(t => t.path);

  // Fetch config files
  const packageJsonRaw = await raw("package.json");
  const requirementsRaw = await raw("requirements.txt");
  const cargoTomlRaw = await raw("Cargo.toml");
  const pyprojectRaw = await raw("pyproject.toml");
  const gemfileRaw = await raw("Gemfile");

  let name = repoName;
  let description = repoInfo.description || "";
  let version = "";
  let license = repoInfo.license?.spdx_id || "";
  let language = repoInfo.language || "";
  let deps = {};
  let scripts = {};

  if (packageJsonRaw) {
    try {
      const p = JSON.parse(packageJsonRaw);
      name = p.name || name;
      description = p.description || description;
      version = p.version || version;
      Object.assign(deps, p.dependencies, p.devDependencies);
      scripts = p.scripts || {};
    } catch {}
  }

  if (requirementsRaw) {
    for (const line of requirementsRaw.split("\n")) {
      const m = line.match(/^([a-zA-Z0-9_.-]+)([><=!~]+.+)?/);
      if (m) deps[m[1]] = m[2] || "*";
    }
  }

  if (cargoTomlRaw) {
    const m = cargoTomlRaw.match(/\[dependencies\]([\s\S]*?)(?=\[|$)/);
    if (m) {
      for (const line of m[1].split("\n")) {
        const dm = line.match(/^(\w[\w-]*)\s*=\s*["{]([^"}]+)/);
        if (dm) deps[dm[1]] = dm[2];
      }
    }
  }

  // Build file tree
  function buildTree() {
    const lines = [`${repoName}/`];
    const dirs = new Set();
    for (const f of allFiles) {
      const parts = f.split("/");
      for (let i = 1; i < parts.length; i++) {
        dirs.add(parts.slice(0, i).join("/"));
      }
    }
    const sortedDirs = [...dirs].sort();
    const sortedFiles = [...allFiles].sort();
    const all = new Set();
    for (const d of sortedDirs) all.add(d);
    for (const f of sortedFiles) all.add(f);
    for (const item of [...sortedDirs, ...sortedFiles]) {
      const depth = item.split("/").length;
      const prefix = "  ".repeat(depth - 1) + "├── ";
      lines.push(prefix + item.split("/").pop() + (dirs.has(item) ? "/" : ""));
    }
    return lines.slice(0, 60).join("\n");
  }

  const depEntries = Object.entries(deps);
  const depTable = depEntries.length
    ? depEntries.slice(0, 30).map(([k, v]) => `| \`${k}\` | ${v} |`).join("\n")
    : "None";

  const scriptEntries = Object.entries(scripts);
  const scriptTable = scriptEntries.length
    ? scriptEntries.slice(0, 10).map(([k, v]) => `| \`${k}\` | \`${v}\` |`).join("\n")
    : "None";

  const treeStr = buildTree();

  const readme = `# ${name}

${description ? `${description}\n\n` : ""}## Table of Contents

- [Installation](#installation)
- [Usage](#usage)
${scriptEntries.length ? "- [Scripts](#scripts)\n" : ""}${depEntries.length ? "- [Dependencies](#dependencies)\n" : ""}- [File Tree](#file-tree)
- [Contributing](#contributing)
- [License](#license)

## Installation

\`\`\`bash
git clone https://github.com/${full}.git
cd ${name}
\`\`\`

## Usage

\`\`\`bash
readmegen ${name}
\`\`\`

_Generated via GitHub API — run readmegen locally for AI-powered prose._${scriptEntries.length ? `

## Scripts

| Script | Command |
|--------|---------|
${scriptTable}` : ""}${depEntries.length ? `

## Dependencies

| Package | Version |
|---------|---------|
${depTable}` : ""}

## File Tree

\`\`\`
${treeStr}
\`\`\`

## Contributing

Contributions are welcome! Please open an issue or submit a pull request.

## License

${license || "MIT"}

---

_Generated by [readmegen](https://github.com/Cravex1862/readmegen)_
`;

  res.json({ content: readme });
}
